"""
AEGIS V4 — FastAPI app.

Mounts every V4 route, runs startup tasks (DB migration, monitor
coroutine), serves the frontend statically. Bound to localhost only.

Run:
    uvicorn backend.main:app --host 127.0.0.1 --port 8000
"""

from __future__ import annotations

import asyncio
import json
from typing import Optional

from fastapi import FastAPI, HTTPException, Request, WebSocket, WebSocketDisconnect
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, StreamingResponse

from . import (
    config, db, inference, monitor, records, retrieval,
    scenarios, system_status, transcription, handoff,
    intake, orchestrator, llm_agents, procedural_steps,
)
from fastapi.responses import Response
from .models import (
    EncounterCreate, EventCreate, ReasonRequest, RetrievalQuery,
)

# V4 §1 lock-down — CORS to a single origin, no wildcards.
_V4_CORS = ["http://127.0.0.1:8000"]

# V6 — sentinel scenario_id for encounters generated by the LLM intake
# flow (POST /api/encounter/begin). These encounters store their step
# graph on the encounter event chain rather than in scenarios.SCENARIOS.
LLM_SCENARIO_ID = "__llm__"


app = FastAPI(title="AEGIS V4 Backend", version=config.BUILD_VERSION)

app.add_middleware(
    CORSMiddleware,
    allow_origins=_V4_CORS,
    allow_credentials=False,
    allow_methods=["GET", "POST", "OPTIONS"],
    allow_headers=["*"],
)


@app.on_event("startup")
async def _startup() -> None:
    db.migrate()
    await monitor.start()
    try:
        await retrieval.warmup()
    except Exception as e:
        print(f"[startup] retrieval warmup deferred: {e}")
    try:
        await transcription.warmup()
    except Exception as e:
        print(f"[startup] transcription warmup deferred: {e}")


@app.on_event("shutdown")
async def _shutdown() -> None:
    await monitor.stop()


# =====================================================================
# Static
# =====================================================================
@app.get("/")
async def index() -> FileResponse:
    return FileResponse(config.FRONTEND_DIR / "index.html")


@app.get("/styles.css")
async def styles() -> FileResponse:
    return FileResponse(config.FRONTEND_DIR / "styles.css", media_type="text/css")


@app.get("/app.js")
async def app_js() -> FileResponse:
    return FileResponse(config.FRONTEND_DIR / "app.js",
                        media_type="application/javascript")


@app.get("/crisis_panel.js")
async def crisis_panel_js() -> FileResponse:
    return FileResponse(config.FRONTEND_DIR / "crisis_panel.js",
                        media_type="application/javascript")


# V6 — ambient background layer (self-contained under frontend/ambient/).
# Whitelisted by extension so a stray file in that directory can't be
# served unintentionally.
_AMBIENT_TYPES = {
    ".css":  "text/css",
    ".js":   "application/javascript",
    ".svg":  "image/svg+xml",
}


@app.get("/ambient/{filename}")
async def ambient_asset(filename: str) -> FileResponse:
    # Reject any traversal attempt; only allow plain filenames.
    if "/" in filename or ".." in filename:
        raise HTTPException(404)
    ext = "." + filename.rsplit(".", 1)[-1].lower() if "." in filename else ""
    media_type = _AMBIENT_TYPES.get(ext)
    if media_type is None:
        raise HTTPException(404)
    path = config.FRONTEND_DIR / "ambient" / filename
    if not path.exists():
        raise HTTPException(404)
    return FileResponse(path, media_type=media_type)


# ----- Crisis Mode (non-expert one-screen UI) -----
@app.get("/crisis")
async def crisis_page() -> FileResponse:
    return FileResponse(config.FRONTEND_DIR / "crisis.html")


@app.get("/crisis.css")
async def crisis_css() -> FileResponse:
    return FileResponse(config.FRONTEND_DIR / "crisis.css", media_type="text/css")


@app.get("/crisis.js")
async def crisis_js() -> FileResponse:
    return FileResponse(config.FRONTEND_DIR / "crisis.js",
                        media_type="application/javascript")


@app.get("/api/intake/questions")
async def api_intake_questions(context: Optional[str] = None) -> dict:
    return {"questions": intake.get_default_intake_questions(context)}


@app.post("/api/crisis")
async def api_crisis(body: dict) -> dict:
    """Run the offline orchestrator and return the one-screen response.

    Routes through the local LLM (LM Studio / Ollama) via llm_agents
    when reachable; falls back to deterministic stubs otherwise so the
    endpoint never breaks.

    Accepts either:
        {"responses": {...}, "scenario_id"?: str}
            — guided-form responses, normalized via intake
        {"encounter": {...}, "scenario_id"?: str}
            — already-structured encounter dict
        {..., "scenario_id"?: str}
            — treated as guided-form responses

    When scenario_id is present and known, scenario.primer_prompt /
    scenario.case / scenario.steps are merged into the encounter as
    `scenario_context` so the LLM bundle is scenario-aware. The
    Procedural Checklist on the frontend uses the bundle's `top_actions`
    (with per-item keywords for extraction matching) as its live source
    of truth, falling back to scenarios.steps when the LLM is offline.
    """
    body = body if isinstance(body, dict) else {}
    scenario_id = body.get("scenario_id")
    scenario = scenarios.get(scenario_id) if scenario_id else None

    if "responses" in body:
        encounter = intake.build_structured_encounter(
            body.get("responses") or {}, scenario=scenario
        )
    elif "encounter" in body:
        encounter = body.get("encounter") or {}
        if scenario and "scenario_context" not in encounter:
            encounter["scenario_context"] = {
                "id": scenario.get("id"),
                "case": scenario.get("case"),
                "primer_prompt": scenario.get("primer_prompt"),
                "steps": list(scenario.get("steps") or []),
            }
    else:
        encounter = intake.build_structured_encounter(body, scenario=scenario)

    try:
        out = await orchestrator.run_encounter_async(
            encounter,
            agents=llm_agents.LLM_AGENTS,
            offline_status=llm_agents.status_snapshot(),
        )
    except Exception as exc:                              # noqa: BLE001
        # Frontend uses {fallback: true} to switch to static checklist.
        return {
            "crisis_view": None,
            "fallback": True,
            "scenario_id": scenario_id,
            "error": str(exc),
            "offline_status": llm_agents.status_snapshot(),
        }
    if scenario_id:
        out["scenario_id"] = scenario_id
    return out


@app.get("/health")
async def health() -> dict:
    return {"ok": True, "version": config.BUILD_VERSION,
            "llm_endpoint": config.LLM_ENDPOINT,
            "llm_model": config.LLM_MODEL,
            "embed_model": config.EMBED_MODEL}


# =====================================================================
# Scenarios
# =====================================================================
@app.get("/api/scenarios")
async def list_scenarios():
    return scenarios.public_list()


# =====================================================================
# Encounters & events
# =====================================================================
@app.post("/api/encounter/create")
async def encounter_create(req: EncounterCreate):
    """Create a new encounter; first event is encounter_started."""
    sc = scenarios.get(req.scenario_id)
    if not sc:
        raise HTTPException(404, f"unknown scenario {req.scenario_id}")
    label = req.patient_label or sc.get("patient_label", "PT-—")
    return records.create_encounter(req.scenario_id, label)


@app.get("/api/encounter/{enc_id}")
async def encounter_get(enc_id: str):
    rec = records.get_encounter(enc_id)
    if not rec:
        raise HTTPException(404, "encounter not found")
    return rec


# =====================================================================
# V6 — LLM-driven encounter intake
# =====================================================================
@app.post("/api/encounter/begin")
async def api_encounter_begin(body: dict):
    """Create an encounter from a typed situation. The LLM produces the
    title, patient label, ordered procedural steps, and an initial brief;
    none of these come from the hardcoded ``scenarios`` module.

    Body: ``{situation: str}``. Returns the full encounter scaffold so
    the cockpit can render immediately without further round-trips.
    """
    situation = ((body or {}).get("situation") or "").strip()
    if not situation:
        raise HTTPException(400, "situation is required")

    try:
        intake_data, meta = await llm_agents.intake_to_encounter(situation)
    except inference.LLMError as exc:
        raise HTTPException(503, f"LLM unreachable: {exc}")

    # Create encounter under the LLM sentinel; persist situation + steps
    # as separate events so the audit chain stays append-only.
    enc = records.create_encounter(LLM_SCENARIO_ID, intake_data["patient_label"])
    enc_id = enc["id"]
    records.add_event(enc_id, "operator_situation_set", {"text": situation})
    records.add_event(enc_id, "encounter_steps_set", {
        "title": intake_data["title"],
        "steps": intake_data["steps"],
        "citations": intake_data.get("citations") or [],
    })

    # Compose the initial brief as a chat-ready string. Frontend prepends
    # this as the first assistant turn in the ASK AEGIS panel.
    brief = intake_data["brief"]
    brief_lines: list[str] = []
    summary = brief.get("summary", "").strip()
    head = f"ACUITY: {brief['acuity']}"
    if summary:
        head = f"{head} — {summary}"
    brief_lines.append(head)
    if brief.get("top_actions"):
        brief_lines.append("TOP ACTIONS: " + " ".join(
            f"{i+1}) {a}" for i, a in enumerate(brief["top_actions"])
        ))
    if brief.get("rule_outs"):
        brief_lines.append("RULE OUT: " + " ".join(
            f"{i+1}) {r}" for i, r in enumerate(brief["rule_outs"])
        ))
    brief_text = "\n".join(brief_lines)

    records.add_event(enc_id, "chat_turn", {
        "question": "(initial brief from situation intake)",
        "reply": brief_text[:1000],
        "citations": [],
        "latency_ms": meta.get("latency_ms"),
    })

    return {
        "encounter_id": enc_id,
        "id": enc_id,
        "scenario_id": LLM_SCENARIO_ID,
        "title": intake_data["title"],
        "patient_label": intake_data["patient_label"],
        "steps": intake_data["steps"],
        "citations": intake_data.get("citations") or [],
        "brief": {**brief, "text": brief_text},
        "latency_ms": meta.get("latency_ms"),
        "model": meta.get("model"),
    }


@app.post("/api/encounter/{enc_id}/event")
async def encounter_event(enc_id: str, body: EventCreate):
    """Append a hashed event."""
    if records.get_encounter(enc_id) is None:
        raise HTTPException(404, "encounter not found")
    eid = records.add_event(enc_id, body.event_type, body.payload, body.t_offset_ms)
    return {"ok": True, "event_id": eid}


@app.post("/api/encounter/{enc_id}/end")
async def encounter_end(enc_id: str):
    if records.get_encounter(enc_id) is None:
        raise HTTPException(404)
    return records.end_encounter(enc_id)


@app.get("/api/encounter/{enc_id}/integrity")
async def encounter_integrity(enc_id: str):
    return records.verify_encounter_integrity(enc_id).model_dump()


@app.get("/api/encounters")
async def encounters_list(active_only: bool = False):
    return records.list_encounters(active_only=active_only)


# =====================================================================
# V5 — Procedural step graph (CURRENT STEP card)
# =====================================================================
@app.get("/api/encounter/{enc_id}/procedural-steps")
async def api_proc_steps(enc_id: str):
    """Returns the step graph plus the current step rendering. The cockpit
    consumes this on first paint.

    For hardcoded scenarios, the graph comes from ``procedural_steps._GRAPHS``.
    For LLM-driven encounters (``scenario_id == LLM_SCENARIO_ID``) the graph
    comes from the latest ``encounter_steps_set`` event on the encounter."""
    rec = records.get_encounter(enc_id)
    if rec is None:
        raise HTTPException(404, "encounter not found")
    sid = rec["scenario_id"]
    graph = procedural_steps.graph_for(sid) or []
    if graph:
        current = procedural_steps.initial_step(sid)
        return {
            "scenario_id": sid,
            "current": current,
            "graph": [
                {
                    "id": s["id"],
                    "title": s["title"],
                    "icon": s.get("icon", "pulse"),
                    "instruction": s.get("instruction", ""),
                    "checklist_text": s["checklist_text"],
                    "why_matters": s.get("why_matters", ""),
                    "question": s.get("question"),
                }
                for s in graph
            ],
        }

    # LLM-driven path
    stored = records.get_encounter_steps(enc_id) or {}
    steps = stored.get("steps") or []
    if not steps:
        raise HTTPException(404, "no step graph for encounter")
    # V6 — return the FULL step shape on every graph entry so the
    # cockpit can navigate back to any previous step and re-render the
    # CURRENT STEP card with the original instruction, why_matters,
    # affirmation, icon, and citations. Previously only id/title/
    # checklist_text were sent, which made backward navigation render a
    # blank step body for LLM-driven encounters.
    return {
        "scenario_id": sid,
        "title": stored.get("title"),
        "citations": stored.get("citations") or [],
        "current": procedural_steps.initial_step_in(steps),
        "graph": [
            {
                "id": s["id"],
                "title": s["title"],
                "icon": s.get("icon", "pulse"),
                "instruction": s.get("instruction", ""),
                "checklist_text": s.get("checklist_text", s.get("title", "")),
                "why_matters": s.get("why_matters", ""),
                "affirmation": s.get("affirmation", ""),
                "question": s.get("question"),
            }
            for s in steps
        ],
    }


@app.post("/api/encounter/{enc_id}/advance-step")
async def api_advance_step(enc_id: str, body: dict):
    """Advance the procedural step. Body: {step_id, decision?}.
    Writes a step_completed event to the encrypted record."""
    rec = records.get_encounter(enc_id)
    if rec is None:
        raise HTTPException(404, "encounter not found")
    sid = rec["scenario_id"]
    step_id = body.get("step_id") or ""
    decision = body.get("decision")  # "yes" | "no" | None

    graph = procedural_steps.graph_for(sid)
    if graph:
        cur = procedural_steps.step_for(sid, step_id)
        if not cur:
            raise HTTPException(400, f"unknown step {step_id}")
        nxt = procedural_steps.advance(sid, step_id, decision)
    else:
        stored = records.get_encounter_steps(enc_id) or {}
        steps = stored.get("steps") or []
        cur = procedural_steps.step_in(steps, step_id)
        if not cur:
            raise HTTPException(400, f"unknown step {step_id}")
        nxt = procedural_steps.advance_in(steps, step_id, decision)

    try:
        records.add_event(enc_id, "step_completed", {
            "step_id": step_id,
            "title": cur["title"],
            "decision": decision,
            "next_step_id": (nxt or {}).get("id") if nxt and not nxt.get("complete") else None,
            "complete": bool(nxt and nxt.get("complete")),
        })
    except Exception:
        pass
    return {"ok": True, "next": nxt}


@app.get("/api/encounter/{enc_id}/context-log")
async def api_context_log(enc_id: str):
    """Chronological list of extracted clinical phrases for the left-column
    CONTEXT LOG. Synthesized from the encounter's events."""
    rec = records.get_encounter(enc_id)
    if rec is None:
        raise HTTPException(404, "encounter not found")
    sid = rec["scenario_id"]
    out: list[dict] = []
    # Seed for fresh encounter
    started_ms = (rec.get("events") or [{}])[0].get("t_offset_ms", 0)
    for s in procedural_steps.context_log_seed(sid):
        out.append({"t": s["t"], "text": s["text"], "kind": "seed"})

    def _fmt(ms: int) -> str:
        s = max(0, int(ms // 1000))
        return f"{s // 3600:02d}:{(s % 3600) // 60:02d}:{s % 60:02d}"

    for ev in rec.get("events") or []:
        et = ev.get("event_type")
        ts = _fmt(int(ev.get("t_offset_ms") or 0))
        p = ev.get("payload") or {}
        if et == "extraction_completed":
            txt = (p.get("summary") or {}).get("phrase") or p.get("phrase")
            if txt:
                out.append({"t": ts, "text": txt, "kind": "extracted"})
        elif et == "step_completed":
            out.append({"t": ts,
                        "text": f"Step complete: {p.get('title','')}",
                        "kind": "step"})
        elif et == "operator_phrase":
            out.append({"t": ts, "text": p.get("text", ""),
                        "kind": "extracted"})
        elif et == "operator_situation_set":
            txt = p.get("text", "")
            if txt:
                out.append({"t": ts, "text": f"SITUATION: {txt}",
                            "kind": "situation"})
    return {"entries": out}


# =====================================================================
# V5 — Operator-supplied situation (left-column SITUATION panel)
# =====================================================================
@app.get("/api/encounter/{enc_id}/situation")
async def api_situation_get(enc_id: str):
    """Return the most recent operator-set situation text for an
    encounter so the cockpit can prefill the SITUATION textarea on
    page load. Empty string if none has been set."""
    rec = records.get_encounter(enc_id)
    if rec is None:
        raise HTTPException(404, "encounter not found")
    latest_text = ""
    latest_t = 0
    for ev in rec.get("events") or []:
        if ev.get("event_type") != "operator_situation_set":
            continue
        t = int(ev.get("t_offset_ms") or 0)
        if t >= latest_t:
            latest_t = t
            latest_text = (ev.get("payload") or {}).get("text", "")
    return {"text": latest_text, "t_offset_ms": latest_t}


@app.post("/api/encounter/{enc_id}/situation")
async def api_situation_set(enc_id: str, body: dict):
    """Persist the operator-supplied situation as an encounter event.
    Body: {text}. Write-only; consumers read via the GET above or
    pass the text along on each /api/chat request."""
    rec = records.get_encounter(enc_id)
    if rec is None:
        raise HTTPException(404, "encounter not found")
    text = (body.get("text") or "").strip()
    if not text:
        raise HTTPException(400, "text is required")
    records.add_event(enc_id, "operator_situation_set", {"text": text})
    return {"ok": True, "len": len(text)}


# =====================================================================
# V5 — Multi-turn chat (ASK AEGIS), situation-aware, RAG-grounded
# =====================================================================
_CHAT_SYSTEM_PROMPT = (
    "You are AEGIS, an offline clinical decision-support assistant for "
    "non-expert first responders in austere environments.\n"
    "Hard rules:\n"
    "  - Never make a diagnostic claim. Use 'consider', 'rule out', "
    "'treat as high risk until ruled out', 'escalate'.\n"
    "  - Be brief. 1-3 short sentences per reply unless the user asks "
    "for detail. Plain language. No jargon a medic wouldn't recognize.\n"
    "  - When supporting evidence is present in the [CORPUS] block, "
    "cite the chunk id in square brackets like [TCCC-TQ-PLACE]. If no "
    "chunk supports an answer, say so and suggest what the operator "
    "should ask or check next.\n"
    "  - The [SITUATION] and [CURRENT STEP] blocks are ground truth "
    "about the encounter. Use them. Do not contradict them.\n"
    "  - Never invent vitals, names, or events not present in the "
    "context.\n"
    "Briefing format (when the user asks for an encounter brief or "
    "to be briefed): respond with three short labeled lines, each on "
    "its own line, citing chunks where possible:\n"
    "  ACUITY: red | yellow | green — one short reason.\n"
    "  TOP ACTIONS: 1) ... 2) ... 3) ... [CHUNK]\n"
    "  RULE OUT: 1) ... 2) ... 3) ... [CHUNK]\n"
    "Otherwise reply conversationally per the rules above."
)


def _format_chat_user_prompt(question: str, situation: str,
                             current_step: dict | None,
                             chunks: list[dict]) -> str:
    parts: list[str] = []
    if situation:
        parts.append(f"[SITUATION]\n{situation.strip()}")
    if current_step and (current_step.get("title")
                         or current_step.get("instruction")):
        title = current_step.get("title", "").strip()
        instr = current_step.get("instruction", "").strip()
        parts.append(
            f"[CURRENT STEP]\n{title}"
            + (f"\n{instr}" if instr else "")
        )
    if chunks:
        parts.append("[CORPUS]\n" + inference._format_chunks(chunks))
    parts.append(f"[QUESTION]\n{question.strip()}")
    return "\n\n".join(parts)


@app.post("/api/chat")
async def api_chat(body: dict):
    """Multi-turn chat for the ASK AEGIS panel. Body:
        {encounter_id, scenario_id?, situation, history[], current_step?}
    history is a list of {role: 'user'|'assistant', content: str}.
    The latest user turn IS in history (last entry); we extract it
    for retrieval, then build a single user message that wraps the
    question with situation + current_step + RAG context.

    Returns {reply, citations[], latency_ms, model}.
    """
    enc_id = (body or {}).get("encounter_id") or ""
    scenario_id = (body or {}).get("scenario_id")
    situation = (body or {}).get("situation") or ""
    history = (body or {}).get("history") or []
    current_step = (body or {}).get("current_step")

    if not history or history[-1].get("role") != "user":
        raise HTTPException(400, "history must end with a user turn")
    question = (history[-1].get("content") or "").strip()
    if not question:
        raise HTTPException(400, "empty user question")

    # RAG grounding — k=3 keeps the prompt tight for fast turns.
    # For LLM-driven encounters (no fixed scenario), pass None so the
    # retrieval layer searches the full corpus rather than boosting
    # chunks tagged with a scenario the operator never picked.
    rag_filter = scenario_id if scenario_id and scenario_id != LLM_SCENARIO_ID \
        else None
    try:
        chunks = await retrieval.retrieve(question, rag_filter, k=3)
    except Exception:
        chunks = []

    user_prompt = _format_chat_user_prompt(
        question, situation, current_step, chunks,
    )

    # Build messages: system + prior history (excluding latest user)
    # + the wrapped latest user turn. Cap history to last 8 turns to
    # keep the prompt under Gemma 4's context budget at low latency.
    prior = [
        {"role": h["role"], "content": h.get("content", "")}
        for h in history[:-1] if h.get("role") in ("user", "assistant")
        and (h.get("content") or "").strip()
    ][-8:]
    messages = (
        [{"role": "system", "content": _CHAT_SYSTEM_PROMPT}]
        + prior
        + [{"role": "user", "content": user_prompt}]
    )

    try:
        reply, meta = await inference.chat_completion(messages)
    except inference.LLMError as exc:
        raise HTTPException(503, f"chat unreachable: {exc}")

    # Extract citation chip ids from [BRACKETS] in the reply text and
    # match against the retrieved chunk ids; surface only the chunks
    # the model actually cited so the UI doesn't overstate grounding.
    import re as _re
    cited_ids = set(_re.findall(r"\[([A-Z][A-Z0-9_-]{2,})\]", reply))
    citations = [
        {"citation_id": c.get("citation_id"),
         "supporting_quote": (c.get("text") or "")[:240]}
        for c in chunks if c.get("citation_id") in cited_ids
    ]

    if enc_id:
        try:
            records.add_event(enc_id, "chat_turn", {
                "question": question[:500],
                "reply": reply[:1000],
                "citations": [c["citation_id"] for c in citations],
                "latency_ms": meta.get("latency_ms"),
            })
        except Exception:
            pass

    return {
        "reply": reply,
        "citations": citations,
        "latency_ms": meta.get("latency_ms"),
        "model": meta.get("model"),
    }


# =====================================================================
# Retrieval
# =====================================================================
@app.post("/api/retrieve")
async def api_retrieve(q: RetrievalQuery):
    chunks = await retrieval.retrieve(q.query, q.scenario_id, q.top_k)
    return {"chunks": chunks}


@app.get("/api/retrieve/chunk/{citation_id}")
async def api_chunk(citation_id: str):
    chunk = await retrieval.by_id(citation_id)
    if not chunk:
        raise HTTPException(404, "citation not in local index")
    return chunk


# =====================================================================
# Transcription (WebSocket)
# =====================================================================
@app.websocket("/api/transcribe")
async def ws_transcribe(ws: WebSocket):
    await ws.accept()
    try:
        await transcription.handle(ws)
    except WebSocketDisconnect:
        return


# =====================================================================
# Reasoning (SSE)
# =====================================================================
@app.post("/api/reason")
async def api_reason(req: ReasonRequest):
    rec = records.get_encounter(req.encounter_id)
    if rec is None:
        raise HTTPException(404, "encounter not found")
    scenario_id = req.scenario_id or rec["scenario_id"]

    async def event_gen():
        # Meta with retrieved chunks (frontend uses to populate ref panel)
        try:
            chunks = await retrieval.retrieve(
                req.transcript or scenarios.get(scenario_id)["primer_prompt"],
                scenario_id, 6,
            )
        except Exception:
            chunks = []
        yield _sse({"type": "meta", "model": (
            config.LLM_MODEL if config.INFERENCE_MODE == "live"
            else "SCRIPTED // V4"
        ), "retrieved": chunks})

        async for tok in inference.stream_reasoning(
            scenario_id, req.transcript, encounter_id=req.encounter_id
        ):
            yield _sse({"type": "token", "text": tok})

        yield _sse({"type": "done", "tps": inference.LAST_TPS or 28.0})
        yield "data: [DONE]\n\n"

    return StreamingResponse(event_gen(), media_type="text/event-stream")


def _sse(obj) -> str:
    return f"data: {json.dumps(obj, ensure_ascii=False)}\n\n"


# =====================================================================
# Vitals (per-tick evolution)
# =====================================================================
@app.post("/api/vitals")
async def api_vitals(body: dict):
    sid = body.get("scenario_id", "")
    sc = scenarios.get(sid)
    if not sc:
        # V6 — LLM-driven encounters have no scenario in scenarios.SCENARIOS;
        # fall back to a generic battlefield-keyed arc so the vitals panel
        # still animates while the encounter is in progress.
        if sid == LLM_SCENARIO_ID:
            sc = {"vital_arc_key": "battlefield"}
        else:
            raise HTTPException(404)
    return {"vitals": scenarios.vitals_for(
        sc, int(body.get("elapsed_ms") or 0), body.get("checklist") or []
    )}


# =====================================================================
# Network monitor (SSE)
# =====================================================================
@app.get("/api/network/stream")
async def network_stream(request: Request):
    async def gen():
        q = monitor.subscribe()
        try:
            last = monitor.last()
            if last:
                yield _sse(last)
            while True:
                if await request.is_disconnected(): break
                try:
                    item = await asyncio.wait_for(q.get(), timeout=10)
                    yield _sse(item)
                except asyncio.TimeoutError:
                    yield ": keepalive\n\n"
        finally:
            monitor.unsubscribe(q)
    return StreamingResponse(gen(), media_type="text/event-stream")


@app.get("/api/system/probes")
async def api_probes():
    return {"probes": monitor.history()}


# =====================================================================
# System status
# =====================================================================
@app.get("/api/system/status")
async def api_system_status():
    # V5 — async variant probes the LLM endpoint at the same time it
    # gathers local telemetry. The cockpit's SYS overlay polls every 4s,
    # which is slow enough to absorb the round-trip cost.
    return await system_status.status_snapshot_with_health()


# =====================================================================
# V4 — The four LLM endpoints (§4)
# =====================================================================
@app.post("/api/extract")
async def api_extract(body: dict):
    """Extract structured facts from a voice transcript."""
    transcript = body.get("transcript", "")
    enc_id = body.get("encounter_id", "")
    scenario = body.get("scenario_name", "")
    elapsed = int(body.get("elapsed_seconds", 0) or 0)
    out = await inference.extract_facts(transcript, enc_id, scenario, elapsed)
    if enc_id:
        try:
            records.add_event(enc_id, "extraction_completed",
                              {"summary": _extract_summary(out)})
        except Exception:
            pass
    return out


def _extract_summary(out: dict) -> dict:
    return {
        "vitals_count": len(out.get("vitals_observed") or []),
        "interventions_count": len(out.get("interventions_performed") or []),
        "confidence": out.get("extraction_confidence"),
    }


@app.post("/api/qa")
async def api_qa(body: dict):
    """Reference QA — operator question against the curated corpus."""
    q = body.get("question", "")
    sc = body.get("scenario_context")
    enc_id = body.get("encounter_id")
    out = await inference.answer_question(q, sc)
    if enc_id:
        try:
            records.add_event(enc_id, "qa_query",
                              {"question": q[:200],
                               "answer_type": out.get("answer_type")})
        except Exception:
            pass
    return out


@app.post("/api/nudges")
async def api_nudges(body: dict):
    """Compute compliance nudges against current encounter state."""
    state = body.get("encounter_state") or {}
    out = await inference.compute_nudges(state)
    enc_id = state.get("encounter_id")
    if enc_id and out.get("nudges"):
        for n in out["nudges"]:
            try:
                records.add_event(enc_id, "nudge_issued", n)
            except Exception:
                pass
    return out


@app.post("/api/handoff/build")
async def api_handoff_build(body: dict):
    """V6 — Build the comprehensive single-PDF patient transfer document.
    No more zip wrapper, no separate .sig / .pub / verifier files —
    every clinically relevant fact about the encounter (situation,
    initial brief, procedural steps performed with completion times,
    citations with supporting quotes) is rendered in the PDF, with the
    integrity hash and Ed25519 signature printed in the document footer
    for chain-of-custody. Returns application/pdf."""
    enc_id = (body or {}).get("encounter_id", "")
    if records.get_encounter(enc_id) is None:
        raise HTTPException(404, "encounter not found")

    pdf_bytes, manifest = handoff.build_transfer_pdf(enc_id)
    headers = {
        "Content-Disposition": f'attachment; filename="{manifest["filename"]}"',
        "X-AEGIS-Bundle-Hash": manifest["integrity_hash"],
        "X-AEGIS-Signature": manifest["signature_hex"],
        "X-AEGIS-Pub-Fingerprint": manifest["device_pub_fingerprint"],
    }
    records.add_event(enc_id, "handoff_packet_built", {
        "filename": manifest["filename"],
        "size_bytes": manifest["size_bytes"],
        "integrity_hash": manifest["integrity_hash"],
    })
    return Response(content=pdf_bytes, media_type="application/pdf",
                    headers=headers)


@app.post("/api/aar")
async def api_aar(body: dict):
    """Generate an after-action review for a completed encounter.

    Returns the structured AAR as a single JSON object. Frontend renders
    the `summary` field through a typewriter effect at the established
    28 cps cadence — the typewriter pacing is purely a UI concern, the
    LLM call itself is non-streaming JSON.
    """
    enc_id = body.get("encounter_id", "")
    rec = records.get_encounter(enc_id)
    if not rec:
        raise HTTPException(404, "encounter not found")
    out = await inference.generate_aar(rec)
    try:
        records.add_event(enc_id, "aar_generated", {
            "documentation_quality": out.get("documentation_quality"),
            "summary_present": bool((out.get("summary") or "").strip()),
        })
    except Exception:
        pass
    return out


@app.post("/api/aar/stream")
async def api_aar_stream(body: dict):
    """V5 — true streaming AAR via Server-Sent Events.

    The frontend's existing typewriter consumes `event: token` messages
    at the established 28 cps visual cadence. The LLM may emit faster
    or slower; the consumer paces.

    Note: the AAR is a structured JSON object, not free-form prose.
    This endpoint streams the *raw model response text* (which the
    backend then parses to JSON post-stream and writes as an event).
    The typewriter renders this directly as the AAR's narrative
    `summary` paragraph during the handoff packet generation moment.
    """
    from sse_starlette.sse import EventSourceResponse  # type: ignore

    enc_id = body.get("encounter_id", "")
    rec = records.get_encounter(enc_id)
    if not rec:
        raise HTTPException(404, "encounter not found")

    chunks = await retrieval.retrieve(
        "protocol compliance review", rec.get("scenario_id"), k=4,
    )
    chunks_block = inference._format_chunks(chunks)
    record_json = json.dumps(rec, default=str, indent=2)[:8000]
    system, user = (
        await __import__("asyncio").get_event_loop().run_in_executor(
            None,
            lambda: __import__("backend.prompts", fromlist=["render_user_prompt"])
                    .render_user_prompt(
                        "aar",
                        encounter_record_json=record_json,
                        chunks_formatted=chunks_block,
                    ),
        )
    )

    async def event_gen():
        full = []
        try:
            async for token in inference.stream_llm(system, user):
                full.append(token)
                yield {"event": "token", "data": json.dumps({"token": token})}
        except inference.LLMError as exc:
            yield {"event": "error",
                   "data": json.dumps({"error": str(exc)})}
            return
        yield {"event": "done", "data": json.dumps({})}
        # Persist the full AAR text as an event so the handoff packet can
        # reference it later.
        try:
            records.add_event(enc_id, "aar_streamed", {
                "raw_text": "".join(full)[:4000],
            })
        except Exception:
            pass

    return EventSourceResponse(event_gen())
